[package]
name = "rust-bots"
version = "0.1.0"
authors = ["Ponder Stibbons Club"]
edition = "2018"

[dependencies]
rand = "0.7.0"
amethyst = "0.11.0"
amethyst_renderer = "0.10.4"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
